version: '3'

services:
  db:
    image: mariadb:latest
    networks:
      - nginx-docker_interna
    env_file: mariadb.env
    volumes:
      - db:/var/lib/mysql
    hostname: mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx-docker_interna
    ports:
      - 9001:9001
    env_file: etherpad.env
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

volumes:
  db:

networks:
  nginx-docker_interna:
    external: true
